### ISSUE TITLE
Blog Suggestion

### ISSUE THREAD

**Issue by mazz** [danschultzer/ansible-phoenix-build#2]
This may be helpful for others when generating passwords with the vaultfile. On your blog at https://dreamconception.com/tech/phoenix-automated-build-and-deploy-made-simple/ you have:

> Create .ansible/apps/production/host_vars/MY_HOST (remember to change the MY_HOST filename to the domain of your production website), and add the encrypted secrets one by one by running ansible-vault encrypt_string --vault-password-file=.ansible/.vault_pass.txt. You should hit ctrl-d twice (not enter) to encrypt the secret. Paste them into your MY_HOST file so it looks similar to this:

I would point out that for ansible 2.4 and higher you can now use ```--stdin-name``` to manually enter a passphrase. So for example we can make two keys to be pasted into the ```MY_HOST``` file like this:

```
ansible-vault encrypt_string --vault-id .ansible/.vault_pass.txt --stdin-name 'secret_key_base'
<enter the passphrase><CTRL-D><CTRL-D>
<copy to clipboard and paste into MY_HOST>
ansible-vault encrypt_string --vault-id .ansible/.vault_pass.txt --stdin-name 'database_password'
<enter the passphrase><CTRL-D><CTRL-D>
<copy to clipboard and paste into MY_HOST>
```

**Comment by danschultzer** [comment]
Thanks for the suggestion, it'll make it easier! I'll update the guide.
