### ISSUE TITLE
Postgrex -- tcp connect (localhost:5432): connection refused

### ISSUE THREAD

**Issue by mazz** [danschultzer/ansible-phoenix-build#3]
Deploying the docker app locally seems to have port 5432 closed because after doing

```
../../py27env/bin/ansible-playbook -i apps/build/inventory apps/build/build.yml -vvv
docker attach ansible_phoenix_build_build_server
cd build/_build/prod/rel/ansible_phoenix_build
bin/ansible_phoenix_build foreground
```

Then repeatedly:

03:15:55.984 [error] Postgrex.Protocol (#PID<0.1316.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused

Any suggestions?

**Comment by danschultzer** [comment]
You'll need to have postgres running in your docker container. The [prepare-deploy-docker](https://github.com/danschultzer/ansible-phoenix-build/blob/edbc1586508f208efa570f7523b0e5e536e812ec/bin/prepare-deploy-docker) script does this for you when you want to test that the app release works locally (`sh bin/prepare-deploy-docker`). By default, postgres is not installed as you won't need it for the build process.

**Comment by mazz** [comment]
Thanks, I'm running into other issues at the moment(psql not found) but could be from something else I did so will close this for now.
