### ISSUE TITLE
different behavior, same commands, almost: bin/deploy vs. ansible-playbook -i apps/production/inventory apps/production/deploy.yml -vvv

### ISSUE THREAD

**Issue by mazz** [danschultzer/ansible-phoenix-build#5]
on the remote machine, I do:
`create a remote `deploy` user(a sudoer)`
`add my deployment machine public rsa key to /home/deploy/.ssh`
`sudo chmod 700 -R ~/.ssh && chmod 600 ~/.ssh/authorized_keys`
then in /etc/sudoers:
`deploy ALL=NOPASSWD: /bin/systemctl restart ansible_phoenix_build`
adding a new service to `/etc/systemd/system/ansible_phoenix_build.service` as in the README.md file

while in the `.ansible` dir I try: `ansible-playbook -i apps/production/inventory apps/production/deploy.yml -vvv`

I get the error where rsync fails:

```sh
fatal: [maz.me]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --rsync-path=sudo -u deploy rsync --out-format=<<CHANGED>>%i %n%L /tmp/ansible_phoenix_build/_build/prod/rel/ansible_phoenix_build/ deploy@maz.me:/u/apps/ansible_phoenix_build/releases/2018.01.021957",
    "invocation": {
        "module_args": {
            "_local_rsync_path": "rsync",
            "_substitute_controller": false,
            "archive": true,
            "checksum": false,
            "compress": true,
            "copy_links": false,
            "delete": true,
            "dest": "deploy@maz.me:/u/apps/ansible_phoenix_build/releases/2018.01.021957",
            "dest_port": null,
            "dirs": false,
            "existing_only": false,
            "group": null,
            "links": null,
            "mode": "push",
            "owner": null,
            "partial": false,
            "perms": null,
            "private_key": null,
            "recursive": true,
            "rsync_opts": null,
            "rsync_path": "sudo -u deploy rsync",
            "rsync_timeout": 0,
            "set_remote_user": true,
            "src": "/tmp/ansible_phoenix_build/_build/prod/rel/ansible_phoenix_build/",
            "ssh_args": null,
            "times": null,
            "verify_host": false
        }
    },
    "msg": "Warning: Permanently added 'maz.me,96.126.108.34' (ECDSA) to the list of known hosts.\r\nrsync: connection unexpectedly closed (8 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/io.c(453) [sender=2.6.9]\n",
    "rc": 12
}
```
  
while in the `ansible-phoenix-build` dir I do: `bin/deploy`
I get the error:
```sh
fatal: [maz.me]: UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1514941963.299496-109181809637189 `\" && echo ansible-tmp-1514941963.299496-109181809637189=\"` echo ~/.ansible/tmp/ansible-tmp-1514941963.299496-109181809637189 `\" ), exited with result 1",
    "unreachable": true
}
```

What do the two errors mean? I believe with the former command I am much closer to deploying successfully. With the former is the issue that I am running the command with `--root`?

**Comment by danschultzer** [comment]
1. Can you get into the server with `ssh deploy@maz.me`? (it seems like you can)
2. Does `/u/apps/ansible_phoenix_build/releases/` exists, and is it accessible for the `deploy` user?

In `bin/deploy` you can remove this from the command: `\  --connection=docker --user=root`. It's just there for local deploy test.

**Comment by danschultzer** [comment]
Just read the error codes for rsync. I'm sure it's because `/u/apps/ansible_phoenix_build/releases/` isn't accessible. If you create it and run `chown -R deploy /u/apps/ansible_phoenix_build/` it should work!

**Comment by danschultzer** [comment]
I've updated the readme with these details: https://github.com/danschultzer/ansible-phoenix-build#deploy-to-remote-server

**Comment by mazz** [comment]
Thanks! That fixed it. I just have to figure out why postgresql does not appear to be installed remotely(getting `"04:07:19.947 [error] Postgrex.Protocol (#PID<0.183.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused",)`
